#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$doc = <<<DOC
Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)
  gendiff [--format <fmt>] <firstFile> <secondFile>

Options:
  -h --help                     Show this screen
  -v --version                  Show version
  --format <fmt>                Report format [default: stylish]
DOC;

$args = Docopt::handle($doc, array('version'=>'gendiff 1.0'));

if (isset($args['<firstFile>']) && isset($args['<secondFile>'])) {
    $firstFile = $args['<firstFile>'];
    $secondFile = $args['<secondFile>'];
    $format = $args['--format'] ?? 'stylish';

    echo "Comparing files: $firstFile and $secondFile\n";
    echo "Using format: $format\n";
} else {
    echo $doc;
}