name: CI

on:
push:
 branches: [ main ]
pull_request:
 branches: [ main ]

jobs:
build:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout@v2
 - name: Setup PHP
   uses: shivammathur/setup-php@v2
   with:
     php-version: '7.4'
 - name: Install dependencies
   run: composer install
 - name: Run linter
   run: make lint
 - name: Run tests
   run: make test
- name: Test & publish code coverage
uses: paambaati/codeclimate-action@v3.0.0
env:
 CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
with:
 coverageCommand: make test-coverage
 debug: true
